import fs from 'fs';
import path from 'path';
import os from 'os';
import { StorageService } from './storage.js';
import { config } from '../config.js';

export interface CodexSyncResult {
  success: boolean;
  message: string;
  configDir: string;
  authPath: string;
  configPath: string;
  authContent?: Record<string, any>;
  configToml?: string;
  cliCommand?: string;
}

export class CliSyncService {
  private static instance: CliSyncService;
  private storage = StorageService.getInstance();

  private constructor() {}

  public static getInstance(): CliSyncService {
    if (!CliSyncService.instance) {
      CliSyncService.instance = new CliSyncService();
    }
    return CliSyncService.instance;
  }

  /**
   * Resolves the Codex home directory (~/.codex or ~/.chatgpt)
   */
  public getCodexDir(): string {
    const home = os.homedir();
    const codexDir = path.join(home, '.codex');
    const chatgptDir = path.join(home, '.chatgpt');

    if (fs.existsSync(codexDir)) {
      return codexDir;
    }
    if (fs.existsSync(chatgptDir)) {
      return chatgptDir;
    }
    return codexDir;
  }

  /**
   * Inspects the current Codex configuration on the system
   */
  public inspectCodex(): CodexSyncResult {
    const codexDir = this.getCodexDir();
    const authPath = path.join(codexDir, 'auth.json');
    const configPath = path.join(codexDir, 'config.toml');

    let authContent: Record<string, any> = {};
    let configToml = '';

    try {
      if (fs.existsSync(authPath)) {
        authContent = JSON.parse(fs.readFileSync(authPath, 'utf8'));
      }
    } catch {}

    try {
      if (fs.existsSync(configPath)) {
        configToml = fs.readFileSync(configPath, 'utf8');
      }
    } catch {}

    const proxySettings = this.storage.getProxySettings();
    const port = proxySettings.port || config.proxyPort || 8090;
    const host = proxySettings.allowLan ? '127.0.0.1' : (proxySettings.host || '127.0.0.1');
    const baseUrl = `http://${host}:${port}/v1`;

    const keys = this.storage.getApiKeys().filter(k => k.enabled);
    const activeKey = keys[0]?.key || proxySettings.masterApiKey || 'sk-ant2api-default';

    return {
      success: true,
      message: 'Codex configuration status inspected',
      configDir: codexDir,
      authPath,
      configPath,
      authContent,
      configToml,
      cliCommand: `codex --base-url ${baseUrl} -k ${activeKey}`
    };
  }

  /**
   * Synchronizes Codex configuration files (auth.json & config.toml) to point to Ant2api
   */
  public syncCodex(customApiKey?: string, selectedModel = 'gemini-3.7-flash'): CodexSyncResult {
    const codexDir = this.getCodexDir();
    const authPath = path.join(codexDir, 'auth.json');
    const configPath = path.join(codexDir, 'config.toml');

    const proxySettings = this.storage.getProxySettings();
    const port = proxySettings.port || config.proxyPort || 8090;
    const host = proxySettings.allowLan ? '127.0.0.1' : (proxySettings.host || '127.0.0.1');
    const baseUrl = `http://${host}:${port}/v1`;

    const keys = this.storage.getApiKeys().filter(k => k.enabled);
    const apiKey = customApiKey || keys[0]?.key || proxySettings.masterApiKey || 'sk-ant2api-master';

    try {
      if (!fs.existsSync(codexDir)) {
        fs.mkdirSync(codexDir, { recursive: true });
      }

      // 1. Write or update auth.json
      let authObj: Record<string, any> = {};
      if (fs.existsSync(authPath)) {
        try {
          authObj = JSON.parse(fs.readFileSync(authPath, 'utf8'));
        } catch {}
      }

      authObj.OPENAI_API_KEY = apiKey;
      authObj.OPENAI_BASE_URL = baseUrl;
      fs.writeFileSync(authPath, JSON.stringify(authObj, null, 2), 'utf8');

      // 2. Write or update config.toml
      const tomlContent = `# Generated by Ant2api Proxy
model_provider = "custom"
model = "${selectedModel}"
review_model = "${selectedModel}"
model_reasoning_effort = "high"
disable_response_storage = true
network_access = "enabled"

[model_providers.custom]
name = "Ant2api Proxy"
base_url = "${baseUrl}"
wire_api = "responses"
requires_openai_auth = true
`;

      fs.writeFileSync(configPath, tomlContent, 'utf8');

      return {
        success: true,
        message: `Successfully synchronized Codex config to ${codexDir}`,
        configDir: codexDir,
        authPath,
        configPath,
        authContent: authObj,
        configToml: tomlContent,
        cliCommand: `codex`
      };
    } catch (err: any) {
      return {
        success: false,
        message: `Failed to sync Codex config: ${err.message}`,
        configDir: codexDir,
        authPath,
        configPath
      };
    }
  }
}
